language: node_js
node_js: node
services:
- mongodb
deploy:
  provider: heroku
  api_key:
    secure: gDdiot6w1/NYuwiXLPy1a3Kje1vhrSPvOzzBsjUuHDrQ0fXN+200Nry67fRloXAREwhqrnYRk1M49lgqW9R1xkXjUpwgTcs3oe8CmWBfk7EeL/Hxzb2Ahsi9LFrCc1Mp8NBjR3EhQOSG37UpAV4BX++o5k7DcFHGiUuZVYJu02qe/aKcR/2to+HNfWQvYhVU4ru7dTh6Oux03SfAPH+eOPsSotua+Z+8MKNERRydFDo62dNZ2DHvbQ4bOXNozd2oVmhU/mXYmuC3ctrr0Jam104HJuXx7Zl3QqIvvhOCAuA/BzjM82bN9u6ZV1ONev3LHgTydve9heFMyoSMjrFdkno1of2ubOWCxN/h6bdjVsTG+MQl/0dFaQr/0CqH4XFruL6SxhOGJ9JJTTYgFVe/gcQXJjAWKrEOKZRgr4+4Mf2fCF/UYMUbTiB9hx5egqEi0W+DjNT1H6m2TZvlgTPexcEE4dEQQYUheucUcKx03xHL7C0bTSChqhkA2KyOxj6k3x1ETzAJzn5z6CfU0TTWiilsNEqH/eYW/w7POt5NFFaW+Mw8YCiN6ZbHAl5Aw+CFiVE2jMdD1cgPiNOIS2xUtkQdM0fkXpX5xk7XqP691eMRy2a4ComnWUVCOYn+Fcj1V/dysfhctZPJPcKEjmcHOQqXeahj20RKXDaR/bSfBX8=
  app: secret-brushlands-10612
  on:
    repo: carabus/archery-tracker-api
